name: Publish

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - 'package.json'
      - '**/*.md'

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: prod
    env:
      GITHUB_TOKEN: ${{ secrets.GH_ADMIN_TOKEN }}
      NPM_TOKEN: ${{ secrets.GH_ADMIN_TOKEN }}
      NODE_AUTH_TOKEN: ${{ secrets.GH_ADMIN_TOKEN }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com
          cache: yarn

      - name: Install Dependencies
        run: yarn install --no-progress --frozen-lockfile

      - name: Automated Version Bump
        id: version-bump
        uses: phips28/gh-action-bump-version@v9.0.31

      - name: Publish
        run: yarn publish --new-version ${{ steps.version-bump.outputs.newTag }} --no-git-tag-version
